// Predefined DSA and CP topics for questions
export const QUESTION_TOPICS = [
  "Arrays",
  "Strings",
  "Linked Lists",
  "Stacks",
  "Queues",
  "Trees",
  "Binary Trees",
  "Binary Search Trees",
  "Graphs",
  "Hash Tables",
  "Heaps",
  "Dynamic Programming",
  "Greedy",
  "Backtracking",
  "Divide and Conquer",
  "Recursion",
  "Sorting",
  "Searching",
  "Binary Search",
  "Two Pointers",
  "Sliding Window",
  "Math",
  "Number Theory",
  "Geometry",
  "Bit Manipulation",
  "Combinatorics",
  "Game Theory",
  "Graphs - DFS",
  "Graphs - BFS",
  "Shortest Path",
  "Minimum Spanning Tree",
  "Trie",
  "Segment Tree",
  "Fenwick Tree",
  "Union Find"
] as const

export type QuestionTopic = typeof QUESTION_TOPICS[number]
